name: build

on:
  push:
    branches:
      - master
  pull_request:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: current
          dependency-graph: generate-and-submit

      - name: Cache konan dependencies
        uses: actions/cache@v4
        with:
          path: ~/.konan
          key: ${{ runner.os }}-gradle-${{ hashFiles('*.gradle.kts') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Build artifact
        env:
          TELEGRAM_ID: ${{ secrets.TELEGRAM_ID }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
          BOT_ID: ${{ secrets.BOT_ID }}
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          BOT_TOKEN_2: ${{ secrets.BOT_TOKEN_2 }}
          CHANNEL_ID: ${{ secrets.CHANNEL_ID }}
        run: ./gradlew koverXmlReport

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        with:
          files: telegram-bot/build/reports/kover/report.xml
          verbose: true
