name: Dev build snap

on:
  push:
    branches:
      - dev

permissions:
  contents: write
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 11

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3-beta
        with:
          gradle-version: current

      - name: Get build version
        id: version
        run: |
          echo "git_hash=$(git rev-parse --short "$GITHUB_SHA")" >> "$GITHUB_ENV"
          echo "date=$(date +'%y%m%d')" >> "$GITHUB_ENV"

      - name: Build artifact
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        run: ./gradlew publishAllPublicationsToGHPackagesRepository -PlibVersion=dev-${{ env.date }}~${{ env.git_hash }}
