name: GH Packages Autorelease

on:
  push:
    paths:
      - 'buildSrc/**'
      - 'api-sentinel/**'
      - 'telegram-bot/**'
      - 'ktnip/**'
      - 'webapps/**'
      - 'ktgram-utils/**'
      - 'ktgram-config-toml/**'
      - 'ktor-starter/**'
      - 'spring-ktgram-starter/**'

jobs:
  publish:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref_type == 'branch' && github.ref != 'refs/heads/master' && !startsWith(github.ref, 'refs/heads/renovate/')
    strategy:
      matrix:
        module: [
          ":telegram-bot",
          ":ktnip",
          ":webapps",
          ":ktgram-utils",
          ":ktgram-config-toml",
          ":ktor-starter",
          ":spring-ktgram-starter"
        ]
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - name: Set up JDK 17
        uses: actions/setup-java@de7274f081f381c8f8158605e0321c36c376e2e6 # v6
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Get build version
        id: version
        run: |
          echo "git_branch=${GITHUB_REF#refs/heads/}" >> "$GITHUB_ENV"
          echo "git_hash=$(git rev-parse --short "$GITHUB_SHA")" >> "$GITHUB_ENV"
          echo "date=$(date +'%y%m%d')" >> "$GITHUB_ENV"


      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@3f5f9adaf7d9fecd50b5935e54106014257a94e6 # v6.4.0
        with:
          gradle-version: current

      - name: Cache konan dependencies
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6
        with:
          path: ~/.konan
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/libs.versions.toml')}}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Publish to Gh
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        run: ./gradlew ${{ matrix.module }}:publishAllPublicationsToGHPackagesRepository -PlibVersion=${{ env.git_branch }}-${{ env.date }}~${{ env.git_hash }}  --no-parallel