name: Packages Cleanup

on:
  schedule:
    - cron: "0 6 * * 1"
  workflow_dispatch:

jobs:
  cleanup:
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package_name: [
          "eu.vendeli.telegram-bot",
          "eu.vendeli.telegram-bot-jvm",
          "eu.vendeli.telegram-bot-js",
          "eu.vendeli.telegram-bot-linuxx64",
          "eu.vendeli.telegram-bot-mingwx64",
          "eu.vendeli.ksp",
          "eu.vendeli.ksp-jvm",
          "eu.vendeli.ktor-starter",
          "eu.vendeli.ktor-starter-jvm",
          "eu.vendeli.ktgram-utils",
          "eu.vendeli.ktgram-utils-js",
          "eu.vendeli.ktgram-utils-jvm",
          "eu.vendeli.ktgram-utils-linuxx64",
          "eu.vendeli.ktgram-utils-mingwx64",
          "eu.vendeli.spring-ktgram-starter",
          "eu.vendeli.spring-ktgram-starter-jvm",
          "eu.vendeli.ktgram-botctx-redis",
          "eu.vendeli.ktgram-botctx-redis-jvm",
          "eu.vendeli.ktgram-config-env",
          "eu.vendeli.ktgram-config-env-jvm",
          "eu.vendeli.ktgram-config-env-js",
          "eu.vendeli.ktgram-config-env-linuxx64",
          "eu.vendeli.ktgram-config-env-mingwx64",
          "eu.vendeli.ktgram-config-toml",
          "eu.vendeli.ktgram-config-toml-jvm",
          "eu.vendeli.ktgram-config-toml-linuxx64",
          "eu.vendeli.ktgram-config-toml-mingwx64",
          "eu.vendeli.ktgram-gradle-plugin",
          "eu.vendeli.webapps",
          "eu.vendeli.webapps-js",
          "eu.vendeli.webapps-jvm",
          "eu.vendeli.webapps-linuxx64",
          "eu.vendeli.webapps-mingwx64"
        ]
    steps:
      - name: Delete old versions of ${{ matrix.package_name }}
        uses: actions/delete-package-versions@v5.0.0
        with:
          package-type: maven
          package-name: ${{ matrix.package_name }}
          min-versions-to-keep: 10
