name: Release

permissions:
  contents: write

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

jobs:
  version:
    name: Get version number from tag
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.vars.outputs.version }}
    steps:
      - name: Read version
        id: vars
        # extract tag name without v prefix
        run: echo "version=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
        shell: bash

  publish:
    needs: version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 11

      - name: Setup gradle
        uses: gradle/actions/setup-gradle@v3-beta
        with:
          gradle-version: current

      - name: Prepare to publish
        run: |
          echo '${{secrets.GPG_KEY_CONTENTS}}' | base64 -d > publish_key.gpg
          gpg --quiet --batch --yes --decrypt --passphrase="${{secrets.SECRET_PASSPHRASE}}" \
          --output /home/runner/work/secret.gpg publish_key.gpg

      - name: Publish with Gradle
        env:
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{secrets.SONATYPE_USERNAME}}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{secrets.SONATYPE_PASSWORD}}
        run: ./gradlew publishAllPublicationsToMavenCentralRepository -Psigning.secretKeyRingFile=/home/runner/work/secret.gpg -Psigning.keyId=${{secrets.SIGNING_KEYID}} -Psigning.password=${{secrets.SIGNING_PASSWORD}} -PlibVersion=${{ needs.version.outputs.version }} --no-parallel

      - name: Publish documentation
        uses: JamesIves/github-pages-deploy-action@releases/v4
        with:
          BRANCH: gh-pages
          FOLDER: telegram-bot/build/dokka

  readme:
    needs: publish
    name: Replace version in README.md
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - uses: jacobtomlinson/gha-find-replace@v3
        with:
          find: '[0-9]+.[0-9]+.[0-9]+\"\)'
          replace: "${{ needs.version.outputs.version }}\")"
          include: "**README.md"
      - name: Push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Bump library version.
          branch: master

  create-release:
    needs: publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Extract changelog for version
        id: changelog
        run: |
          ./parse_changelog.sh ${{ needs.version.outputs.version }} > release_notes.md
        shell: bash

      - uses: taiki-e/create-gh-release-action@v1
        with:
          title: $version
          changelog: release_notes.md
          branch: master
          token: ${{ secrets.ACCESS_TOKEN }}