on:
  workflow_dispatch:

name: Scrape Telegram bot API
jobs:
  build:
    name: Scrape
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - name: Set up Python
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7
        with:
          python-version: '3.14'

      - name: Install dependencies
        run: >
          pip install requests==2.32.3 beautifulsoup4==4.12.3 html5lib==1.1

      - name: Scrape API
        run: python buildSrc/src/main/resources/scrape.py

      - name: Push changes
        uses: stefanzweifel/git-auto-commit-action@4a55954c782fc1ea30b9056cd3e7a2b40ca8887d # v7
        with:
          commit_message: Update Bot API spec.
          branch: dev